# -*- coding: utf-8 -*-
"""

This file is generated by AI

使用 NumPy 手写 Self-Attention + 自动反向传播
在 IMDB 数据集上进行情感分类

特点：
- 不使用 PyTorch / TensorFlow
- 使用 NumPy 实现张量运算
- 手写自动求导系统（类似 mini torch）
- 实现 Self-Attention
- 使用 HuggingFace datasets 加载 IMDB

用途：
- 研究 Self-Attention 原理
- 研究 Transformer 基本训练过程
- 理解 Autograd

注意：
这是教学/研究代码，不是高性能实现。
训练会非常慢。
"""

import numpy as np
from datasets import load_dataset
from collections import Counter
import time


MAX_LEN = 256
VOCAB_SIZE = 20000
BATCH_SIZE = 8
EPOCHS = 5

# ============================================================
# 自动求导系统
# ============================================================

class Tensor:
    def __init__(self, data, requires_grad=False):
        self.data = np.array(data, dtype=np.float32)
        self.requires_grad = requires_grad

        self.grad = None
        self.backward_fn = None
        self.parents = []

    def backward(self, grad=None):
        if not self.requires_grad:
            return

        if grad is None:
            grad = np.ones_like(self.data)

        if self.grad is None:
            self.grad = grad
        else:
            self.grad += grad

        if self.backward_fn:
            self.backward_fn(grad)

    # ----------------------
    # 基本运算
    # ----------------------

    def __add__(self, other):
        other = ensure_tensor(other)

        out = Tensor(
            self.data + other.data,
            requires_grad=self.requires_grad or other.requires_grad
        )

        def backward(grad):
            if self.requires_grad:
                self.backward(grad)

            if other.requires_grad:
                other.backward(grad)

        out.backward_fn = backward
        return out

    def __matmul__(self, other):
        other = ensure_tensor(other)

        out = Tensor(
            self.data @ other.data,
            requires_grad=self.requires_grad or other.requires_grad
        )

        def backward(grad):
            if self.requires_grad:
                self.backward(grad @ other.data.T)

            if other.requires_grad:
                other.backward(self.data.T @ grad)

        out.backward_fn = backward
        return out

    def __mul__(self, other):
        other = ensure_tensor(other)

        out = Tensor(
            self.data * other.data,
            requires_grad=self.requires_grad or other.requires_grad
        )

        def backward(grad):
            if self.requires_grad:
                self.backward(grad * other.data)

            if other.requires_grad:
                other.backward(grad * self.data)

        out.backward_fn = backward
        return out

    def sum(self, axis=None, keepdims=False):
        out = Tensor(
            self.data.sum(axis=axis, keepdims=keepdims),
            requires_grad=self.requires_grad
        )

        def backward(grad):
            if self.requires_grad:
                expanded = grad * np.ones_like(self.data)
                self.backward(expanded)

        out.backward_fn = backward
        return out

    def mean(self):
        out = Tensor(
            self.data.mean(),
            requires_grad=self.requires_grad
        )

        def backward(grad):
            if self.requires_grad:
                self.backward(
                    grad * np.ones_like(self.data) / self.data.size
                )

        out.backward_fn = backward
        return out


def ensure_tensor(x):
    if isinstance(x, Tensor):
        return x
    return Tensor(x)


# ============================================================
# 激活函数
# ============================================================

def relu(x):
    out = Tensor(
        np.maximum(0, x.data),
        requires_grad=x.requires_grad
    )

    def backward(grad):
        if x.requires_grad:
            x.backward(grad * (x.data > 0))

    out.backward_fn = backward
    return out


def softmax(x):
    exp = np.exp(x.data - np.max(x.data, axis=-1, keepdims=True))
    probs = exp / np.sum(exp, axis=-1, keepdims=True)

    out = Tensor(probs, requires_grad=x.requires_grad)

    def backward(grad):
        if not x.requires_grad:
            return

        dx = np.zeros_like(x.data)

        for i in range(len(probs)):
            p = probs[i].reshape(-1, 1)
            jacobian = np.diagflat(p) - p @ p.T
            dx[i] = jacobian @ grad[i]

        x.backward(dx)

    out.backward_fn = backward
    return out


def cross_entropy(logits, targets):
    probs = softmax(logits)

    batch_size = logits.data.shape[0]

    log_probs = np.log(
        probs.data[np.arange(batch_size), targets] + 1e-8
    )

    loss_val = -np.mean(log_probs)

    out = Tensor(loss_val, requires_grad=True)

    def backward(grad):
        grad_logits = probs.data.copy()

        grad_logits[np.arange(batch_size), targets] -= 1
        grad_logits /= batch_size

        logits.backward(grad * grad_logits)

    out.backward_fn = backward
    return out


# ============================================================
# Self-Attention
# ============================================================

class SelfAttention:

    def __init__(self, d_model):

        self.Wq = Tensor(
            np.random.randn(d_model, d_model) / np.sqrt(d_model),
            requires_grad=True
        )

        self.Wk = Tensor(
            np.random.randn(d_model, d_model) / np.sqrt(d_model),
            requires_grad=True
        )

        self.Wv = Tensor(
            np.random.randn(d_model, d_model) / np.sqrt(d_model),
            requires_grad=True
        )

        self.params = [self.Wq, self.Wk, self.Wv]

        self.d_model = d_model

    def forward(self, x):

        Q = x @ self.Wq
        K = x @ self.Wk
        V = x @ self.Wv

        scores = Tensor(
            (Q.data @ K.data.transpose(0, 2, 1))
            / np.sqrt(self.d_model),
            requires_grad=True
        )

        attn = softmax(scores)

        out = Tensor(
            attn.data @ V.data,
            requires_grad=True
        )

        return out


# ============================================================
# 模型
# ============================================================

class Model:

    def __init__(self, vocab_size, d_model, num_classes):

        self.embedding = Tensor(
            np.random.randn(vocab_size, d_model) * 0.02,
            requires_grad=True
        )

        self.attn = SelfAttention(d_model)

        self.fc = Tensor(
            np.random.randn(d_model, num_classes) / np.sqrt(d_model),
            requires_grad=True
        )

        self.params = (
            [self.embedding, self.fc]
            + self.attn.params
        )

    def embed(self, x):

        emb = self.embedding.data[x]

        return Tensor(emb, requires_grad=True)

    def forward(self, x):

        x = self.embed(x)

        x = self.attn.forward(x)

        pooled = Tensor(
            x.data.mean(axis=1),
            requires_grad=True
        )

        logits = pooled @ self.fc

        return logits


# ============================================================
# 优化器
# ============================================================

class SGD:

    def __init__(self, params, lr=1e-3):
        self.params = params
        self.lr = lr

    def step(self):

        for p in self.params:

            if p.grad is not None:
                p.data -= self.lr * p.grad

    def zero_grad(self):

        for p in self.params:
            p.grad = None


# ============================================================
# 数据处理
# ============================================================


def tokenize(text):
    text = text.lower()
    return text.split()


def build_vocab(texts):
    print("Building vocabulary...")

    counter = Counter()

    for text in texts:
        counter.update(tokenize(text))

    vocab = {
        word: idx + 2
        for idx, (word, _)
        in enumerate(counter.most_common(VOCAB_SIZE - 2))
    }

    vocab["<PAD>"] = 0
    vocab["<UNK>"] = 1
    
    print(f"Vocabulary size: {len(vocab)}")
    
    return vocab


def encode(text, vocab):

    words = tokenize(text)

    ids = [
        vocab.get(w, 1)
        for w in words[:MAX_LEN]
    ]

    while len(ids) < MAX_LEN:
        ids.append(0)

    return np.array(ids)


# ============================================================
# 加载 IMDB
# ============================================================

print("Loading IMDB dataset...")

dataset = load_dataset("imdb")

train_texts = dataset["train"]["text"][:2000]
train_labels = dataset["train"]["label"][:2000]

test_texts = dataset["test"]["text"][:200]
test_labels = dataset["test"]["label"][:200]


vocab = build_vocab(train_texts)

X_train = np.array([
    encode(t, vocab)
    for t in train_texts
])

y_train = np.array(train_labels)

X_test = np.array([
    encode(t, vocab)
    for t in test_texts
])

y_test = np.array(test_labels)

# ============================================================
# 初始化模型
# ============================================================

model = Model(
    vocab_size=VOCAB_SIZE,
    d_model=32,
    num_classes=2
)

optimizer = SGD(model.params, lr=1e-2)

# ============================================================
# 训练
# ============================================================

def evaluate():
    correct = 0
    for i in range(len(X_test)):
        logits = model.forward(
            X_test[i:i+1]
        )
        pred = np.argmax(logits.data)
        if pred == y_test[i]:
            correct += 1
    # train
    correct_t = 0
    for i in range(len(X_train)):
        logits = model.forward(
            X_train[i:i+1]
        )
        pred = np.argmax(logits.data)
        if pred == y_train[i]:
            correct_t += 1
            
    return correct_t / len(X_train), correct / len(X_test)

print("\nStart training (using smaller dataset)...\n")

for epoch in range(EPOCHS):

    indices = np.arange(len(X_train))
    np.random.shuffle(indices)

    X_train = X_train[indices]
    y_train = y_train[indices]

    total_loss = 0

    start_time = time.time()    

    for i in range(0, len(X_train), BATCH_SIZE):

        xb = X_train[i:i+BATCH_SIZE]
        yb = y_train[i:i+BATCH_SIZE]

        optimizer.zero_grad()

        logits = model.forward(xb)

        loss = cross_entropy(logits, yb)

        loss.backward()

        optimizer.step()

        total_loss += loss.data
        
    
    end_time = time.time()
    
    train_loss = total_loss / len(X_train)
    train_acc, test_acc = evaluate()
    elapsed = end_time - start_time

    print(
        f"Epoch {epoch + 1}/{EPOCHS} | "
        f"Loss: {train_loss:.4f} | "
        f"Train Acc: {train_acc:.4f} | "
        f"Test Acc: {test_acc:.4f} | "
        f"Time: {elapsed:.2f}s"
    )


# ============================================================
# 推理函数
# ============================================================

def predict(text: str) -> str:
    x = encode(text, vocab)
    x = np.expand_dims(x, axis=0)
    logits = model.forward(x)
    
    pred = np.argmax(logits.data, axis=1)[0]
    return "positive" if pred == 1 else "negative"


sample_text = "This movie was amazing and the acting was fantastic"

result = predict(sample_text)

print("\nPrediction example:")
print(sample_text)
print("Sentiment:", result)
