# -*- coding: utf-8 -*-

"""
This file is generated by AI
"""

import time
from collections import Counter

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from datasets import load_dataset


MAX_VOCAB_SIZE = 20000
MAX_LEN = 256
BATCH_SIZE = 64
EMBED_DIM = 128
NUM_HEADS = 4
HIDDEN_DIM = 128
NUM_CLASSES = 2
EPOCHS = 5
LEARNING_RATE = 1e-3

if __name__ == '__main__':
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    print(f"Using device: {DEVICE}")

    print("Loading IMDB dataset...")

    dataset = load_dataset("imdb")

    train_texts = dataset["train"]["text"]
    train_labels = dataset["train"]["label"]

    test_texts = dataset["test"]["text"]
    test_labels = dataset["test"]["label"]


def tokenize(text):
    text = text.lower()
    return text.split()


if __name__ == '__main__':

    print("Building vocabulary...")

    counter = Counter()

    for text in train_texts:
        counter.update(tokenize(text))

    most_common = counter.most_common(MAX_VOCAB_SIZE - 2)

    vocab = {
        "<PAD>": 0,
        "<UNK>": 1,
    }

    for idx, (word, _) in enumerate(most_common, start=2):
        vocab[word] = idx

    print(f"Vocabulary size: {len(vocab)}")


def encode(text):
    tokens = tokenize(text)

    ids = [vocab.get(token, 1) for token in tokens]

    if len(ids) > MAX_LEN:
        ids = ids[:MAX_LEN]
    else:
        ids += [0] * (MAX_LEN - len(ids))

    return ids


class IMDbDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = labels

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        x = torch.tensor(encode(self.texts[idx]), dtype=torch.long)
        y = torch.tensor(self.labels[idx], dtype=torch.long)

        return x, y


if __name__ == '__main__':

    train_dataset = IMDbDataset(train_texts, train_labels)
    test_dataset = IMDbDataset(test_texts, test_labels)

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
    )


class AttentionClassifier(nn.Module):
    def __init__(self, vocab):
        super().__init__()

        self.embedding = nn.Embedding(
            num_embeddings=len(vocab),
            embedding_dim=EMBED_DIM,
            padding_idx=0,
        )

        self.attention = nn.MultiheadAttention(
            embed_dim=EMBED_DIM,
            num_heads=NUM_HEADS,
            batch_first=True,
        )

        self.fc1 = nn.Linear(EMBED_DIM, HIDDEN_DIM)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(HIDDEN_DIM, NUM_CLASSES)

    def forward(self, x):
        # x shape:
        # [batch_size, seq_len]

        emb = self.embedding(x)

        # Self-attention
        attn_output, _ = self.attention(
            emb,
            emb,
            emb,
        )

        # Global average pooling
        pooled = attn_output.mean(dim=1)

        out = self.fc1(pooled)
        out = self.relu(out)
        out = self.fc2(out)

        return out


if __name__ == '__main__':

    model = AttentionClassifier(vocab).to(DEVICE)

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=LEARNING_RATE,
    )


def train_one_epoch():
    model.train()

    total_loss = 0
    total_correct = 0
    total_samples = 0

    start_time = time.time()

    for x, y in train_loader:
        x = x.to(DEVICE)
        y = y.to(DEVICE)

        optimizer.zero_grad()

        logits = model(x)

        loss = criterion(logits, y)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

        preds = torch.argmax(logits, dim=1)

        total_correct += (preds == y).sum().item()
        total_samples += y.size(0)

    end_time = time.time()

    avg_loss = total_loss / len(train_loader)
    accuracy = total_correct / total_samples
    elapsed = end_time - start_time

    return avg_loss, accuracy, elapsed


@torch.no_grad()
def evaluate():
    model.eval()

    total_correct = 0
    total_samples = 0

    for x, y in test_loader:
        x = x.to(DEVICE)
        y = y.to(DEVICE)

        logits = model(x)

        preds = torch.argmax(logits, dim=1)

        total_correct += (preds == y).sum().item()
        total_samples += y.size(0)

    accuracy = total_correct / total_samples

    return accuracy


if __name__ == '__main__':

    print("\nStart training...\n")

    for epoch in range(EPOCHS):
        train_loss, train_acc, train_time = train_one_epoch()

        test_acc = evaluate()

        print(
            f"Epoch {epoch + 1}/{EPOCHS} | "
            f"Loss: {train_loss:.4f} | "
            f"Train Acc: {train_acc:.4f} | "
            f"Test Acc: {test_acc:.4f} | "
            f"Time: {train_time:.2f}s"
        )


@torch.no_grad()
def predict(text):
    model.eval()

    x = torch.tensor(
        [encode(text)],
        dtype=torch.long,
    ).to(DEVICE)

    logits = model(x)

    pred = torch.argmax(logits, dim=1).item()

    return "positive" if pred == 1 else "negative"


if __name__ == '__main__':

    sample_text = "This movie was amazing and the acting was fantastic"

    result = predict(sample_text)

    print("\nPrediction example:")
    print(sample_text)
    print("Sentiment:", result)

    # save
    checkpoint = {
        "model_state_dict": model.state_dict(),
        "vocab": vocab,
        "max_len": MAX_LEN,
    }

    torch.save(checkpoint, "./checkpoint.pth")
    print("\n./checkpoint.pth saved.")
